# https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html
# ~/javaWorkspace/examples/cp-all-in-one (5.3.1-post)
version: '3.7'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.3.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      # https://zookeeper.apache.org/doc/r3.5.1-alpha/zookeeperAdmin.html
      _JAVA_OPTIONS: -Dzookeeper.admin.serverPort=22800
    network_mode: host

  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.3.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      _JAVA_OPTIONS: -Dzookeeper.admin.serverPort=32800
    network_mode: host

  zookeeper-3:
    image: confluentinc/cp-zookeeper:5.3.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      _JAVA_OPTIONS: -Dzookeeper.admin.serverPort=42800
    network_mode: host

  kafka-1:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    network_mode: host
    restart: unless-stopped
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  kafka-2:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    network_mode: host
    restart: unless-stopped
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  kafka-3:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    network_mode: host
    restart: unless-stopped
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  # https://docs.confluent.io/current/ksql/docs/installation/install-ksql-with-docker.html
  ksql-server:
    image: confluentinc/cp-ksql-server:5.3.1
    network_mode: host
    restart: unless-stopped
    depends_on:
      - kafka-1
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "localhost:19092"
      KSQL_HOST_NAME: ksql-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0

  mongo:
    image: mongo:4.2.2-bionic
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_kafkotest_data_dir:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["--replSet", "rs0"]

volumes:
  mongo_kafkotest_data_dir:
