# https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html
# ~/javaWorkspace/examples/cp-all-in-one (5.3.1-post)
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888
    network_mode: host

  kafka-1:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    network_mode: host
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:4.2.2-bionic
    network_mode: host
    volumes:
      - mongo_kafkotest_data_dir:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["--replSet", "rs0"]

volumes:
  mongo_kafkotest_data_dir:
